/**
 * Builds a starter llms.txt from whatever the project told us about itself.
 *
 * This is deliberately a *starter*. A generated llms.txt that nobody edits is a worse
 * machine reading than a short one somebody wrote, so the file says so in its own text and
 * marks what it could not work out. The goal is to get the site from "no machine reading,
 * so the pill cannot render" to "a real file that a human improves in ten minutes".
 *
 * Offline by design. An agent running `npx human-machine-swapper init` is often in a
 * sandbox with no network; a generator that needs one fails exactly where it matters most.
 */

const TODO = "TODO";

export function buildLlmsTxt(facts = {}, { framework } = {}) {
  const name = facts.name || "This site";
  const summary = facts.description || `${TODO}: one sentence on what this site is.`;

  const lines = [];
  lines.push(`# ${name}`);
  lines.push("");
  lines.push(`> ${wrapOne(summary)}`);
  lines.push("");
  lines.push("## About");
  lines.push("");
  if (facts.description) {
    lines.push(wrap(facts.description));
  } else {
    lines.push(`${TODO}: a paragraph or two a language model can quote about ${name}.`);
  }
  lines.push("");

  if (facts.headings && facts.headings.length) {
    lines.push("## Sections");
    lines.push("");
    for (const h of facts.headings) lines.push(`- ${h}`);
    lines.push("");
  }

  lines.push("## Key facts");
  lines.push("");
  lines.push(`Q: What is ${name}?`);
  lines.push(`A: ${facts.description ? wrapOne(facts.description) : `${TODO}`}`);
  lines.push("");
  lines.push(`Q: What can I do on ${name}?`);
  lines.push(`A: ${TODO}`);
  lines.push("");

  if (facts.url) {
    lines.push("## Links");
    lines.push("");
    lines.push(`- Website: ${facts.url}`);
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(
    wrap(
      `This file was generated by human-machine-swapper init${
        framework ? ` from a ${framework} project` : ""
      }. It is a starting point, not a finished machine reading: replace every ${TODO} and cut anything that is not true. The convention is documented at https://llmstxt.org`
    )
  );
  lines.push("");

  return lines.join("\n");
}

/** How many TODOs a human still owes this file. The CLI reports it rather than pretending. */
export function countTodos(text) {
  return (text.match(new RegExp(TODO, "g")) || []).length;
}

function wrap(text, width = 92) {
  const words = String(text).split(/\s+/).filter(Boolean);
  const out = [];
  let line = "";
  for (const w of words) {
    if (line && (line + " " + w).length > width) {
      out.push(line);
      line = w;
    } else {
      line = line ? line + " " + w : w;
    }
  }
  if (line) out.push(line);
  return out.join("\n");
}

/** Single line, for places where a newline would break the format (the > blurb, a Q/A). */
function wrapOne(text) {
  return String(text).replace(/\s+/g, " ").trim();
}
